#!/bin/bash

# Evaulate
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-10 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-20 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-30 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-40 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-50 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-60 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-70 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-80 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-90 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-100 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True

