#!/bin/bash

# Evaulate
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-100 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-200 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-300 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-400 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-500 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-600 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-700 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-800 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-900 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True
python scripts/eval.py /rds/user/co-grab1/hpc-work/anyburl/predictions-max-1000 /rds/user/co-grab1/hpc-work/anyburl/train.csv /rds/user/co-grab1/hpc-work/anyburl/valid.csv /rds/user/co-grab1/hpc-work/anyburl/test.csv /rds/user/co-grab1/hpc-work/anyburl/heads.pkl /rds/user/co-grab1/hpc-work/anyburl/tails.pkl True

